# -*- coding: utf-8 -*-
"""DrawFunctionChart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RcVnmH_R3yLNt_zc5ZSW0sK2pauyIqvU
"""

#run one time
import pylab

x = [2, 4, 5, 6, 7, 8, 9]
y = [4, 7, 1, 4, 5, 6, 7]
pylab.plot(x,y)

a = 2
b = 1
x = list(range(-10,11))
y = []
for i in x:
  y.append(a * i - b)
pylab.plot(x,y)
pylab.title(f'f(x) = {a}*x - {b}')
pylab.grid(True)
#pylab.show()

a = 2
b = 1
x = list(range(-10,11))
y = [(a * i ** 2 + b * i + c) for i in x]
pylab.plot(x,y)
pylab.title(f'f(x) = {a}*x^2 + {b}')
pylab.grid(True)

a = -4
b = 0
c = 2
x = list(range(-10,11))
y = [(a * i ** 2 + b * i + c) for i in x]
pylab.plot(x,y, 'ro')
pylab.title(f'f(x) = {a}*x^2 + {b}*x + {c}')
pylab.grid(True)

x1 = list(range(-100, 0))
x11 = [i / 10 for i in x1]
y1 = [1 / i for i in x11]
x2 = list(range(1, 101))
x22= [i / 10 for i in x2]
y2 = [1 / i for i in x22]
'''
osyx = [0, 0, 0]
osyy = [-10, 0, 10]
osxx = [-10, 0, 10]
osxy = [0, 0, 0]
pylab.plot(osyx,osyy)
pylab.plot(osxx,osxy)
'''
pylab.plot(x11,y1)
pylab.plot(x22,y2)
pylab.title('f(x) = 1/x')
pylab.grid(True)

usd = open('KursUSD.txt').read().split('\n')
usd = [float(i) for i in usd]
#print(usd)
x = list(range(len(usd)))
pylab.plot(x, usd)
#pylab.plot(x, usd, 'ro')
pylab.title('Kurs dolara')
pylab.grid(True)

x = list(range(1, 16))
on = [6, 5.9, 5.8, 5.6, 8.2, 8.1, 8.4, 8.1, 7.6, 7.2, 7.3, 7.8, 7.4, 7.1, 6.9]
pb95 = [6, 5.8, 5.7, 5.5, 6.5, 6.4, 7, 7.8, 7.2, 6.8, 6.3, 6.9, 6.7, 6.6, 6.5]
pylab.plot(x, on, 'ko-')
pylab.plot(x, pb95, 'go-')
pylab.title('Cena paliwa')
pylab.grid(True)