# -*- coding: utf-8 -*-
"""Python-WSE-2023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wg-GjELaAeiV00IMc13UUqbskCaIONkF

# Polecenie print
"""

print("Hello world!", end=" * ")
print("Hello Mars!")
print("\tHello\n\"Venus!\"")
print('Hello "Venus!"')
print("A", "u", "t", "o", sep="-")
print("A"+"u"+"t"+"o", sep="-")
print("#"+"F"*6)
# parametr end określa co ma wypisać na końcu linii
# \n - nowa linia
# \t - tabulator

"""# Zmienne"""

v1 = 6
v2 = 4
print(v1, "+", v2, "=", v1 + v2)
print(v1, "-", v2, "=", v1 - v2)
print(v1, "*", v2, "=", v1 * v2)
print(v1, "/", v2, "=", v1 / v2)
print(f"{v1} % {v2} = {v1 % v2}")
print(f"{v1} ** {v2} = {v1 ** v2}")

v3 = 1
v4 = 1.5
v5 = True
v6 = "text"
print("v3 = ", v3, type(v3))
print("v4 = ", v4, type(v4))
print("v5 = ", v5, type(v5))
print("v6 = ", v6, type(v6))
v3 = "jeden"
v6 = 2.0
print("v3 = ", v3, type(v3))
print("v6 = ", v6, type(v6))

drukuj = print
drukuj("czy wpisze?")
drukuj(v1, "+", v2, "=", v1+v2)

v10 = "abc"
print(v10, id(v10))
v11 = "abc"
print(v11, id(v11))
v12 = 64
print(v12, id(v12))
v13 = 64
print(v13, id(v13))
v13 = 61
print(v13, id(v13))
v13 = 64
print(v13, id(v13))

# v14 = 512
# print(v14, id(v14))
# v15 = 512
# print(v15, id(v15))

v7 = 6
v8 = 9
print(v7, v8)
v7, v8 = v8+3, v7-1
print(v7, v8)

int1 = 256
int2 = 0x100
int3 = 0o400
int4 = 0b100000000
print(int1, int2, int3, int4)

re1 = 100.
re2 = 0.10
re3 = .10
re4 = 1e3
print(re1, re2, re3, re4)

# txt = input("Wpisz dowolny tekst:")
# print(txt)
num1 = int(input("Pierwsza liczba:"))
num2 = float(input("Druga liczba:"))
print(f"{num1} + {num2} = {num1+num2}")

"""# Instrukcje warunkowe"""

year_birth = int(input("Podaj rok urodzenia:"))
current_year = 2023
age = current_year - year_birth
print("Wiek: ", age)
if age >= 18:
  print("Pełnoletni")
else:
  print("Niepełnoletni")

x = 1
y = 3
if x > 0 and y >0:
  print("obie dodatnie")

num1 = 10
num2 = 10.
if num1 == num2:
  print(f"1. {num1} = {num2}")
if num1 is num2:
  print(f"2. {num1} is {num2}")
if num1 is not num2:
  print(f"3. {num1} is not {num2}")
num2 = int(num2)
if num1 is int(num2):
  print(f"4. {num1} is {num2}")

number = float(input("Podaj liczbę:"))
if number % 2 == 0:
  print(f"Liczba {number} jest parzysta.")
else:
  print(f"Liczba {number} nie jest parzysta.")
  print("tak sobie sprawdzam blok kodu")
print("i jeszcze troche tekstu")